exclude:
  - 'LICENSE'
  - 'README.md'
  - 'jekyll.out'
  - 'jekyll.err'

pygments:    true

permalink:     '/:categories/:year-:month-:day-:title.html'
paginate_path: 'page:num'

markdown:      redcarpet
